const SEED_DESTINATIONS = [
  {
    name: "Udaipur",
    slug: "udaipur",
    state: "Rajasthan",
    region: "Rajasthan",
    tagline: "Royal Romance by the Lakes",
    description: "The City of Lakes is the undisputed jewel of regal Indian destination weddings. Featuring floating marble palaces, tranquil lake view lawns, and heritage royal hospitality.",
    heroImage: "https://images.unsplash.com/photo-1615880484746-a134be9a6ecf?auto=format&fit=crop&w=1600&q=85",
    gallery: [
      "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1567157577867-05ccb1388e66?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=1000&q=80"
    ],
    weddingStyles: ["Royal", "Palace", "Lakeside", "Heritage", "Luxury"],
    bestMonths: ["October – March"],
    bestMonthsList: ["October", "November", "December", "January", "February", "March"],
    climate: "Lake",
    nearestAirport: "Maharana Pratap Airport (UDR)",
    airportDistance: "22 km (35 mins)",
    idealGuestMin: 100,
    idealGuestMax: 600,
    budgetRange: { min: 35, max: 150 },
    pricing: {
      venueDailyMin: 350000,
      venueDailyMax: 1500000,
      roomNightMin: 9000,
      roomNightMax: 35000,
      foodPerGuestMin: 3500,
      foodPerGuestMax: 8500,
      decorEventMin: 300000,
      decorEventMax: 1200000,
      photographyMin: 250000,
      photographyMax: 800000,
      entertainmentMin: 200000,
      entertainmentMax: 700000,
      transportationMin: 100000,
      transportationMax: 400000,
      plannerPercentage: 12,
      taxPercentage: 18,
      contingencyPercentage: 5
    },
    highlights: [
      "Lakeside floating mandap setups at Lake Pichola",
      "Royal boat baraat entries for groom",
      "Historic 400-year-old Mewar architecture backdrop"
    ],
    considerations: [
      "High demand during peak winter months (Nov-Jan)",
      "Strict noise restriction cutoff at 10:00 PM for outdoor lake venues"
    ],
    experiences: ["Royal Sheesh Mahal Dinner", "Vintage Car Procession", "Sunset Shikara Cruise"],
    faqs: [
      {
        question: "What is the average cost for a 150-guest Udaipur wedding?",
        answer: "A 3-day luxury wedding in Udaipur typically ranges between ₹45 Lakhs to ₹1.2 Crores depending on palace venue choice."
      }
    ],
    featured: true
  },
  {
    name: "Jaipur",
    slug: "jaipur",
    state: "Rajasthan",
    region: "Rajasthan",
    tagline: "The Grand Pink City Extravaganza",
    description: "Jaipur combines magnificent sandstone forts, opulent ballrooms, and vibrant Rajasthani cultural artistry for unforgettable regal weddings.",
    heroImage: "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1600&q=85",
    gallery: [
      "https://images.unsplash.com/photo-1588096344316-f71c8f1f2e6a?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1506461883276-594a12b11cf3?auto=format&fit=crop&w=1000&q=80"
    ],
    weddingStyles: ["Royal", "Palace", "Heritage", "Luxury"],
    bestMonths: ["October – March"],
    bestMonthsList: ["October", "November", "December", "January", "February", "March"],
    climate: "City",
    nearestAirport: "Jaipur International Airport (JAI)",
    airportDistance: "12 km (20 mins)",
    idealGuestMin: 150,
    idealGuestMax: 1000,
    budgetRange: { min: 40, max: 180 },
    pricing: {
      venueDailyMin: 400000,
      venueDailyMax: 1800000,
      roomNightMin: 8000,
      roomNightMax: 30000,
      foodPerGuestMin: 3200,
      foodPerGuestMax: 7500,
      decorEventMin: 350000,
      decorEventMax: 1500000,
      photographyMin: 200000,
      photographyMax: 700000,
      entertainmentMin: 250000,
      entertainmentMax: 800000,
      transportationMin: 120000,
      transportationMax: 500000,
      plannerPercentage: 10,
      taxPercentage: 18,
      contingencyPercentage: 5
    },
    highlights: ["Elephant & Camel welcome processions", "Sprawling fort courtyards", "Excellent flight connectivity from Delhi & Mumbai"],
    considerations: ["Summers (April-July) are extremely hot"],
    experiences: ["Elephant Baraat Entry", "Folk Kalbeliya Dance Night", "Royal Bazaar Welcome"],
    faqs: [],
    featured: true
  },
  {
    name: "South Goa",
    slug: "south-goa",
    state: "Goa",
    region: "Goa",
    tagline: "Serene Beachfront Luxury & Sunset Vows",
    description: "Golden sands, whispering coconut palms, and 5-star beachfront resorts. South Goa offers intimate, romantic, and soul-stirring seaside weddings.",
    heroImage: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1600&q=85",
    gallery: [
      "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1000&q=80"
    ],
    weddingStyles: ["Beach", "Tropical", "Bohemian", "Modern", "Pastel"],
    bestMonths: ["November – April"],
    bestMonthsList: ["November", "December", "January", "February", "March", "April"],
    climate: "Beach",
    nearestAirport: "Manohar International Airport (GOX) / Dabolim (GOI)",
    airportDistance: "30 km (45 mins)",
    idealGuestMin: 50,
    idealGuestMax: 400,
    budgetRange: { min: 25, max: 110 },
    pricing: {
      venueDailyMin: 250000,
      venueDailyMax: 1000000,
      roomNightMin: 7000,
      roomNightMax: 25000,
      foodPerGuestMin: 2800,
      foodPerGuestMax: 6500,
      decorEventMin: 250000,
      decorEventMax: 900000,
      photographyMin: 200000,
      photographyMax: 600000,
      entertainmentMin: 180000,
      entertainmentMax: 600000,
      transportationMin: 80000,
      transportationMax: 300000,
      plannerPercentage: 10,
      taxPercentage: 18,
      contingencyPercentage: 5
    },
    highlights: ["Direct beach mandap access at sunset", "Cocktail sundown parties", "Relaxed coastal vibe for guests"],
    considerations: ["Monsoon season (June to September) restricts outdoor beach setups"],
    experiences: ["Sunset Beach Mandap", "Tropical Pool Party Mehendi", "Seafood BBQ Sundowner"],
    faqs: [],
    featured: true
  },
  {
    name: "Jaisalmer",
    slug: "jaisalmer",
    state: "Rajasthan",
    region: "Rajasthan",
    tagline: "Golden Fort & Arabian Nights Fantasy",
    description: "The Golden City offers magical desert fort weddings under starlit skies, torchlit sandstone ramparts, and opulent desert camp celebrations.",
    heroImage: "https://images.unsplash.com/photo-1572445271230-a78b5944a659?auto=format&fit=crop&w=1600&q=85",
    gallery: [
      "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=1000&q=80"
    ],
    weddingStyles: ["Desert", "Royal", "Heritage", "Bohemian"],
    bestMonths: ["October – March"],
    bestMonthsList: ["October", "November", "December", "January", "February", "March"],
    climate: "Desert",
    nearestAirport: "Jaisalmer Airport (JSA)",
    airportDistance: "14 km (25 mins)",
    idealGuestMin: 80,
    idealGuestMax: 350,
    budgetRange: { min: 30, max: 95 },
    highlights: ["Sam sand dunes starry night sangeet", "Sandstone palace architecture", "Authentic Manganiyar folk musicians"],
    considerations: ["Cold desert nights in Dec-Jan require outdoor heaters"],
    experiences: ["Dune Buggy Welcome", "Fire Dancers Sangeet", "Golden Sandstone Mandap"],
    featured: true
  },
  {
    name: "Kumarakom",
    slug: "kumarakom",
    state: "Kerala",
    region: "Kerala",
    tagline: "Tranquil Backwater Bliss & Houseboat Romance",
    description: "Nestled along Vembanad Lake, Kumarakom provides lush palm-fringed lawns, heritage Kerala architecture, and serene backwater ceremonies.",
    heroImage: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1600&q=85",
    gallery: [
      "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=1000&q=80"
    ],
    weddingStyles: ["Nature", "Lake", "Traditional", "Tropical", "Minimal"],
    bestMonths: ["October – March"],
    bestMonthsList: ["October", "November", "December", "January", "February", "March"],
    climate: "Lake",
    nearestAirport: "Cochin International Airport (COK)",
    airportDistance: "75 km (1.5 hours)",
    idealGuestMin: 50,
    idealGuestMax: 300,
    budgetRange: { min: 20, max: 70 },
    highlights: ["Bridal boat entry across Vembanad Lake", "Traditional Sadya lunch served on banana leaf", "Kathakali & Chenda Melam performances"],
    considerations: ["High humidity during afternoon ceremonies"],
    experiences: ["Houseboat Sunset Cruise", "Kathakali Performance", "Traditional Sadya Feast"],
    featured: true
  },
  {
    name: "Rishikesh",
    slug: "rishikesh",
    state: "Uttarakhand",
    region: "Uttarakhand",
    tagline: "Sacred Ganges Riverside Vows",
    description: "Surrounded by the Himalayas and the pristine River Ganges, Rishikesh hosts soulful, spiritual, eco-luxury resort weddings.",
    heroImage: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1600&q=85",
    gallery: [
      "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=80"
    ],
    weddingStyles: ["Nature", "Mountain", "Traditional", "Minimal"],
    bestMonths: ["September – April"],
    bestMonthsList: ["September", "October", "November", "February", "March", "April"],
    climate: "Mountain",
    nearestAirport: "Dehradun Jolly Grant Airport (DED)",
    airportDistance: "20 km (30 mins)",
    idealGuestMin: 50,
    idealGuestMax: 250,
    budgetRange: { min: 20, max: 65 },
    highlights: ["Holy Ganga Aarti ceremony for guests", "Serene mountain background mandap", "Pure vegetarian gourmet culinary curation"],
    considerations: ["Alcohol policies vary across riverside properties"],
    experiences: ["Ganga Aarti Blessings", "Himalayan Sunrise Yoga", "Riverside Mandap"],
    featured: true
  },
  {
    name: "Mussoorie",
    slug: "mussoorie",
    state: "Uttarakhand",
    region: "Uttarakhand",
    tagline: "Queen of the Hills & Misty Valley Weddings",
    description: "Charming colonial hill station with panoramic Himalayan mountain views, crisp pine air, and romantic cliffside luxury hotels.",
    heroImage: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1600&q=85",
    gallery: [],
    weddingStyles: ["Mountain", "Luxury", "Pastel", "Heritage"],
    bestMonths: ["March – June", "September – November"],
    bestMonthsList: ["March", "April", "May", "September", "October", "November"],
    climate: "Mountain",
    nearestAirport: "Dehradun Jolly Grant Airport (DED)",
    airportDistance: "55 km (1.5 hours)",
    idealGuestMin: 60,
    idealGuestMax: 350,
    budgetRange: { min: 30, max: 85 },
    highlights: ["Winterline sunset backdrop for reception", "Heritage luxury properties", "Crisp mountain climate"],
    considerations: ["Mountain road curves for heavy guest buses"],
    experiences: ["Valley View Cocktail Night", "High Tea on Cliff Lawns"],
    featured: true
  },
  {
    name: "Jim Corbett",
    slug: "jim-corbett",
    state: "Uttarakhand",
    region: "Uttarakhand",
    tagline: "Wilderness Romance & Forest Resorts",
    description: "For nature-loving couples, Jim Corbett features riverside forest resorts along the Kosi River surrounded by dense jungle flora.",
    heroImage: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=1600&q=85",
    gallery: [],
    weddingStyles: ["Nature", "Forest", "Bohemian", "Minimal"],
    bestMonths: ["October – April"],
    bestMonthsList: ["October", "November", "December", "January", "February", "March", "April"],
    climate: "Forest",
    nearestAirport: "Pantnagar Airport (PGH) / Dehradun (DED)",
    airportDistance: "80 km (2 hours)",
    idealGuestMin: 80,
    idealGuestMax: 400,
    budgetRange: { min: 20, max: 60 },
    highlights: ["Kosi riverbed mandap backdrop", "Jungle safari experience for wedding guests", "RUSTIC bohemian wood decor"],
    considerations: ["Sound levels restricted after 10 PM near national park zones"],
    experiences: ["Jungle Safari for Guests", "Bonfire Acoustic Evening"],
    featured: true
  },
  {
    name: "Jodhpur",
    slug: "jodhpur",
    state: "Rajasthan",
    region: "Rajasthan",
    tagline: "The Sun City's Royal Fortress Grandeur",
    description: "Dominated by the majestic Mehrangarh Fort, Jodhpur offers imposing heritage fort palaces and royal desert splendor.",
    heroImage: "https://images.unsplash.com/photo-1562979314-bee7453e911c?auto=format&fit=crop&w=1600&q=85",
    gallery: [],
    weddingStyles: ["Royal", "Palace", "Heritage"],
    bestMonths: ["October – March"],
    bestMonthsList: ["October", "November", "December", "January", "February", "March"],
    climate: "Desert",
    nearestAirport: "Jodhpur Airport (JDH)",
    airportDistance: "8 km (15 mins)",
    idealGuestMin: 100,
    idealGuestMax: 700,
    budgetRange: { min: 45, max: 200 },
    highlights: ["Fort illumination during sangeet night", "Royal Rajputana welcome rituals", "Heritage palace ballrooms"],
    considerations: ["Exclusive heritage properties require early bookings"],
    experiences: ["Fort Rampart Gala", "Vintage Camel Procession"],
    featured: true
  },
  {
    name: "Shimla",
    slug: "shimla",
    state: "Himachal Pradesh",
    region: "Himachal Pradesh",
    tagline: "Colonial Charm & Pine Covered Slopes",
    description: "Pine-scented mountain breezes, heritage British colonial architecture, and snow-peaked Himalayan vistas.",
    heroImage: "https://images.unsplash.com/photo-1589802829985-817e51171b92?auto=format&fit=crop&w=1600&q=85",
    gallery: [],
    weddingStyles: ["Mountain", "Heritage", "Pastel"],
    bestMonths: ["March – June", "October – December"],
    bestMonthsList: ["March", "April", "May", "October", "November", "December"],
    climate: "Mountain",
    nearestAirport: "Jubbarhatti Airport (SLV) / Chandigarh (IXC)",
    airportDistance: "22 km (45 mins)",
    idealGuestMin: 50,
    idealGuestMax: 300,
    budgetRange: { min: 25, max: 75 },
    highlights: ["Cedar forest photo shoots", "Heritage grand ballrooms", "Charming hill resort weather"],
    considerations: ["Heavy snowfall in Jan-Feb can disrupt road travel"],
    experiences: ["Heritage Ballroom Waltz", "Pine Lawn High Tea"],
    featured: false
  },
  {
    name: "Manali",
    slug: "manali",
    state: "Himachal Pradesh",
    region: "Himachal Pradesh",
    tagline: "Snowy Peak Romance & Beas River Valley",
    description: "Nested amidst snow-clad peaks and apple orchards, Manali provides an idyllic alpine backdrop for romantic mountain weddings.",
    heroImage: "https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&w=1600&q=85",
    gallery: [],
    weddingStyles: ["Mountain", "Nature", "Bohemian"],
    bestMonths: ["April – June", "September – November"],
    bestMonthsList: ["April", "May", "June", "September", "October", "November"],
    climate: "Mountain",
    nearestAirport: "Kullu-Manali Airport (KUU)",
    airportDistance: "50 km (1.2 hours)",
    idealGuestMin: 40,
    idealGuestMax: 200,
    budgetRange: { min: 20, max: 55 },
    highlights: ["Apple orchard outdoor wedding setups", "Beas river valley backdrop", "Intimate mountain gatherings"],
    considerations: ["Monsoon landslides in July-August"],
    experiences: ["Orchard Lawn Haldi", "Bonfire Sangeet"],
    featured: false
  },
  {
    name: "Srinagar",
    slug: "srinagar",
    state: "Jammu & Kashmir",
    region: "Jammu & Kashmir",
    tagline: "Paradise on Earth & Dal Lake Houseboats",
    description: "Featuring Chinar trees, Mughal gardens, shikara rides on Dal Lake, and breathtaking mountain-enclosed valleys.",
    heroImage: "https://images.unsplash.com/photo-1595815771614-ade9d652a65d?auto=format&fit=crop&w=1600&q=85",
    gallery: [],
    weddingStyles: ["Lake", "Mountain", "Royal", "Nature"],
    bestMonths: ["April – October"],
    bestMonthsList: ["April", "May", "June", "July", "August", "September", "October"],
    climate: "Lake",
    nearestAirport: "Sheikh ul-Alam International Airport (SXR)",
    airportDistance: "15 km (25 mins)",
    idealGuestMin: 50,
    idealGuestMax: 300,
    budgetRange: { min: 30, max: 90 },
    highlights: ["Shikara floral entry", "Mughal garden mandap backdrop", "Kashmiri Wazwan wedding feast"],
    considerations: ["Weather changes quickly; outdoor marquees essential"],
    experiences: ["Dal Lake Shikara Procession", "Wazwan Gourmet Feast"],
    featured: true
  },
  {
    name: "Mahabalipuram",
    slug: "mahabalipuram",
    state: "Tamil Nadu",
    region: "Tamil Nadu",
    tagline: "Coastal Stone Heritage & Bay of Bengal Vows",
    description: "UNESCO World Heritage shore temples meets 5-star beachfront luxury resorts just an hour drive from Chennai.",
    heroImage: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1600&q=85",
    gallery: [],
    weddingStyles: ["Beach", "Heritage", "South Indian", "Luxury"],
    bestMonths: ["November – February"],
    bestMonthsList: ["November", "December", "January", "February"],
    climate: "Beach",
    nearestAirport: "Chennai International Airport (MAA)",
    airportDistance: "55 km (1 hour)",
    idealGuestMin: 100,
    idealGuestMax: 600,
    budgetRange: { min: 25, max: 95 },
    highlights: ["Shore temple architectural inspiration", "Lush coastal sprawling lawns", "Proximity to Chennai international airport"],
    considerations: ["Warm humid climate during daytime"],
    experiences: ["Traditional Carnatic Nadaswaram Procession", "Seaside Mandap"],
    featured: false
  },
  {
    name: "Kochi",
    slug: "kochi",
    state: "Kerala",
    region: "Kerala",
    tagline: "Colonial Heritage & Coastal Elegance",
    description: "Fort Kochi colonial charm, Chinese fishing nets, and luxury island waterfront resorts with deep historic soul.",
    heroImage: "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=1600&q=85",
    gallery: [],
    weddingStyles: ["Heritage", "Coastal", "Minimal", "Traditional"],
    bestMonths: ["October – March"],
    bestMonthsList: ["October", "November", "December", "January", "February", "March"],
    climate: "City",
    nearestAirport: "Cochin International Airport (COK)",
    airportDistance: "35 km (45 mins)",
    idealGuestMin: 80,
    idealGuestMax: 500,
    budgetRange: { min: 22, max: 75 },
    highlights: ["Dutch & Portuguese colonial courtyard venues", "Island luxury resort accessibility", "Fresh coastal seafood curation"],
    considerations: ["Monsoon showers from June to August"],
    experiences: ["Waterfront Sunset Cocktail", "Chenda Melam Entry"],
    featured: false
  },
  {
    name: "Coorg",
    slug: "coorg",
    state: "Karnataka",
    region: "Karnataka",
    tagline: "Coffee Plantation Luxury & Misty Hills",
    description: "Nestled in the Western Ghats, Coorg features sprawling private coffee estate resorts, emerald green hills, and cool mountain air.",
    heroImage: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1600&q=85",
    gallery: [],
    weddingStyles: ["Nature", "Mountain", "Forest", "Pastel"],
    bestMonths: ["October – March"],
    bestMonthsList: ["October", "November", "December", "January", "February", "March"],
    climate: "Forest",
    nearestAirport: "Kannur International Airport (CNN) / Mangalore (IXE)",
    airportDistance: "90 km (2 hours)",
    idealGuestMin: 50,
    idealGuestMax: 250,
    budgetRange: { min: 20, max: 65 },
    highlights: ["Coffee estate green lawn mandap", "Kodava cultural elements", "Serene mist-draped mornings"],
    considerations: ["Road drive required from airport"],
    experiences: ["Coffee Plantation Walk", "Misty Hills Sundowner"],
    featured: false
  },
  {
    name: "Andaman Islands",
    slug: "andaman",
    state: "Andaman & Nicobar",
    region: "Island Destinations",
    tagline: "Exotic Turquoise Ocean & White Sand Vows",
    description: "Crystal clear turquoise waters, pristine white sandy beaches, and untouched tropical rainforest luxuriance for exclusive island weddings.",
    heroImage: "https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?auto=format&fit=crop&w=1600&q=85",
    gallery: [],
    weddingStyles: ["Beach", "Tropical", "Bohemian", "Luxury"],
    bestMonths: ["November – April"],
    bestMonthsList: ["November", "December", "January", "February", "March", "April"],
    climate: "Beach",
    nearestAirport: "Veer Savarkar International Airport (IXZ)",
    airportDistance: "10 km (20 mins)",
    idealGuestMin: 30,
    idealGuestMax: 180,
    budgetRange: { min: 35, max: 120 },
    highlights: ["Havelock Island barefoot beach mandap", "Coral reef scuba diving for wedding guests", "Unrivaled island sunset views"],
    considerations: ["Ferry transfers required between Port Blair and Havelock Island"],
    experiences: ["Barefoot Beach Vows", "Coral Reef Snorkeling Party"],
    featured: true
  },
  {
    name: "Agra",
    slug: "agra",
    state: "Uttar Pradesh",
    region: "Uttar Pradesh",
    tagline: "Eternal Monument of Love Backdrop",
    description: "Celebrate your eternal love story with view of the Taj Mahal, opulent Mughal architecture, and grand luxury resort gardens.",
    heroImage: "https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=1600&q=85",
    gallery: [],
    weddingStyles: ["Royal", "Heritage", "Luxury"],
    bestMonths: ["October – March"],
    bestMonthsList: ["October", "November", "December", "January", "February", "March"],
    climate: "City",
    nearestAirport: "Agra Airport (AGR) / Delhi IGI Airport (DEL)",
    airportDistance: "12 km (25 mins)",
    idealGuestMin: 100,
    idealGuestMax: 600,
    budgetRange: { min: 30, max: 100 },
    highlights: ["Taj Mahal view terrace champagne toast", "Mughal fountain lawn decor", "Fast Yamuna Expressway connection from Delhi"],
    considerations: ["Drones and loud music restricted in close radius of monument"],
    experiences: ["Taj View Sundowner", "Mughlai Royal Feast"],
    featured: false
  },
  {
    name: "Lonavala",
    slug: "lonavala",
    state: "Maharashtra",
    region: "Maharashtra",
    tagline: "Sahyadri Valley Views & Easy Weekend Getaway",
    description: "Nestled in the Sahyadri mountains just 2 hours from Mumbai & Pune, featuring valley view resorts and cool misty weather.",
    heroImage: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1600&q=85",
    gallery: [],
    weddingStyles: ["Mountain", "Nature", "Modern"],
    bestMonths: ["October – March"],
    bestMonthsList: ["October", "November", "December", "January", "February", "March"],
    climate: "Mountain",
    nearestAirport: "Pune Airport (PNQ) / Mumbai Airport (BOM)",
    airportDistance: "70 km (1.5 hours)",
    idealGuestMin: 80,
    idealGuestMax: 500,
    budgetRange: { min: 20, max: 70 },
    highlights: ["2-hour drive from Mumbai and Pune", "Valley view amphitheater mandap", "Spacious resort lawns"],
    considerations: ["Weekend expressway traffic jams"],
    experiences: ["Valley Amphitheater Pheras", "Poolside Mehendi"],
    featured: false
  },
  {
    name: "Pushkar",
    slug: "pushkar",
    state: "Rajasthan",
    region: "Rajasthan",
    tagline: "Spiritual Sacred Lake & Desert Royalty",
    description: "Holy lake town surrounded by desert hills, offering tranquil heritage resorts, pink bougainvillea courtyards, and bohemian charm.",
    heroImage: "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=1600&q=85",
    gallery: [],
    weddingStyles: ["Heritage", "Bohemian", "Desert", "Traditional"],
    bestMonths: ["October – March"],
    bestMonthsList: ["October", "November", "December", "January", "February", "March"],
    climate: "Desert",
    nearestAirport: "Kishangarh Airport (KQH) / Jaipur (JAI)",
    airportDistance: "45 km (50 mins)",
    idealGuestMin: 50,
    idealGuestMax: 350,
    budgetRange: { min: 20, max: 65 },
    highlights: ["Desert camp sangeet celebration", "Bohemian floral mandap setup", "Holy lake temple atmosphere"],
    considerations: ["Avoid Pushkar Camel Fair dates due to heavy crowds"],
    experiences: ["Desert Camp Sangeet", "Bohemian Lake High Tea"],
    featured: false
  },
  {
    name: "Ranthambore",
    slug: "ranthambore",
    state: "Rajasthan",
    region: "Rajasthan",
    tagline: "Royal Wilderness & Fortified Luxury Camps",
    description: "Royal hunting lodge inspired heritage palaces and tented camps situated beside Ranthambore National Park.",
    heroImage: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=1600&q=85",
    gallery: [],
    weddingStyles: ["Forest", "Royal", "Heritage", "Bohemian"],
    bestMonths: ["October – April"],
    bestMonthsList: ["October", "November", "December", "January", "February", "March", "April"],
    climate: "Forest",
    nearestAirport: "Jaipur Airport (JAI)",
    airportDistance: "160 km (3 hours)",
    idealGuestMin: 60,
    idealGuestMax: 300,
    budgetRange: { min: 25, max: 80 },
    highlights: ["Royal luxury canvas tent accommodations", "Tiger safari experience for guests", "Fortress courtyard Mandap"],
    considerations: ["Park closed during monsoon months"],
    experiences: ["Jungle Safari", "Royal Campfire Sangeet"],
    featured: false
  }
];

const SEED_VENUES = [
  {
    name: "Leela Palace Udaipur",
    slug: "leela-palace-udaipur",
    destinationName: "Udaipur",
    heroImage: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1400&q=85",
    gallery: [
      "https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1000&q=80"
    ],
    category: "Lake Palace",
    capacityMax: 400,
    roomCount: 80,
    indoorSpaces: ["Grand Mewar Ballroom", "Sheesh Mahal Dining"],
    outdoorSpaces: ["Lakeside Courtyard", "Guava Garden Lawns", "Outer Jetty Mandap"],
    airportDistance: "25 km",
    venueStyle: "Royal Palace",
    priceTier: "Luxury",
    priceOnRequest: true,
    startingPricePerDay: 1200000,
    amenities: ["Private Boat Arrival", "Lake Pichola Views", "Spa", "Helipad", "Fine Dining"],
    whyCouplesChooseIt: ["Unobstructed views of City Palace across Lake Pichola", "World class royal service and bespoke wedding butler team"],
    thingsToConsider: ["Requires 100% room buy-out during wedding dates"],
    featured: true
  },
  {
    name: "Rambagh Palace Jaipur",
    slug: "rambagh-palace-jaipur",
    destinationName: "Jaipur",
    heroImage: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1400&q=85",
    gallery: [
      "https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=1000&q=80"
    ],
    category: "Heritage Fort",
    capacityMax: 800,
    roomCount: 78,
    indoorSpaces: ["Maharani Ballroom", "Suvarna Mahal"],
    outdoorSpaces: ["Oriental Garden", "Jaipur Lawn", "Panghat Lawn"],
    airportDistance: "11 km",
    venueStyle: "Royal Heritage",
    priceTier: "Luxury",
    priceOnRequest: true,
    startingPricePerDay: 1500000,
    amenities: ["Peacock Gardens", "Polo Grounds", "Vintage Car Fleet", "Royal Welcome"],
    whyCouplesChooseIt: ["Former residence of the Maharaja of Jaipur", "Massive lawns that accommodate grand royal wedding baraats"],
    thingsToConsider: ["Peak wedding dates booked up to 1 year in advance"],
    featured: true
  },
  {
    name: "Taj Exotica Resort & Spa Goa",
    slug: "taj-exotica-goa",
    destinationName: "South Goa",
    heroImage: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1400&q=85",
    gallery: [],
    category: "Beach Resort",
    capacityMax: 500,
    roomCount: 140,
    indoorSpaces: ["Sala Da Banquete", "Sala De Jantar"],
    outdoorSpaces: ["Beachfront Lawns", "Poolside Courtyard", "Sunset Deck"],
    airportDistance: "28 km",
    venueStyle: "Beachfront Luxury",
    priceTier: "Luxury",
    priceOnRequest: false,
    startingPricePerDay: 850000,
    amenities: ["Direct Benaulim Beach Access", "Mediterranean Architecture", "Golf Course"],
    whyCouplesChooseIt: ["Direct private access to golden sands for sunset mandap"],
    thingsToConsider: ["Outdoor sound restrictions apply after 10 PM"],
    featured: true
  },
  {
    name: "Suryagarh Jaisalmer",
    slug: "suryagarh-jaisalmer",
    destinationName: "Jaisalmer",
    heroImage: "https://images.unsplash.com/photo-1572445271230-a78b5944a659?auto=format&fit=crop&w=1400&q=85",
    gallery: [],
    category: "Heritage Fort",
    capacityMax: 350,
    roomCount: 90,
    indoorSpaces: ["Bawdi Hall", "Central Courtyard"],
    outdoorSpaces: ["Sunset Patio", "Sand Dunes Lawn", "Bawdi Pool Amphitheatre"],
    airportDistance: "15 km",
    venueStyle: "Desert Fort",
    priceTier: "Luxury",
    priceOnRequest: true,
    startingPricePerDay: 950000,
    amenities: ["Desert Safaris", "Central Courtyard Bawdi", "Folk Music Troupe"],
    whyCouplesChooseIt: ["Famous venue for celebrity desert royal weddings", "Stunning golden stone architecture"],
    thingsToConsider: ["Chilly winter nights require outdoor heaters"],
    featured: true
  }
];

const SEED_STORIES = [
  {
    title: "Ananya & Kabir’s Palace Romance",
    slug: "ananya-kabir-udaipur",
    coupleNames: "Ananya & Kabir",
    destination: "Udaipur",
    venue: "Leela Palace",
    style: "Royal Palace",
    heroImage: "https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=1400&q=85",
    gallery: [
      "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1000&q=80"
    ],
    story: "Set against the sparkling waters of Lake Pichola, Ananya and Kabir exchanged vows under an antique gold mandap dripping in fresh white mogra and blush garden roses.",
    theme: "Royal Sunset Lake Romance",
    colourPalette: ["Antique Gold", "Blush Pink", "Ivory"],
    guestCount: 160,
    featured: true
  },
  {
    title: "Tara & Rohan’s Sunset Beach Vows",
    slug: "tara-rohan-goa",
    coupleNames: "Tara & Rohan",
    destination: "South Goa",
    venue: "Taj Exotica",
    style: "Beachfront Bohemian",
    heroImage: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1400&q=85",
    gallery: [],
    story: "Barefoot in the sand at sunset, surrounded by lush pampas grass, white orchids, and sea breezes.",
    theme: "Tropical Chic Beach",
    colourPalette: ["Sand Beige", "Ivory", "Sage Green"],
    guestCount: 120,
    featured: true
  }
];

module.exports = {
  SEED_DESTINATIONS,
  SEED_VENUES,
  SEED_STORIES
};
